name: aura_music_kit
description: A professional Flutter plugin to query local device music, manage playlists, and apply audio effects on Android and iOS.
version: 1.0.0
homepage: https://github.com/your_username/aura_music_kit # Replace with your repository URL

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

# The 'plugin' section is crucial for connecting Dart to native code.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.aura_music_kit
        pluginClass: AuraMusicKitPlugin
      ios:
        pluginClass: AuraMusicKitPlugin
